language: python

python:
  - "3.5"
  - "3.6"
  - "nightly"

# Test the nightly build of cpython, but ignore any failures.
# Add separate test environments for the docs and flake8 linter.
matrix:
  allow_failures:
    - python: "nightly"
  include:
    - env: BUILD=docs
    - env: BUILD=pep8
    - env: BUILD=cover

# travis pre-installs some packages that may conflict with our test
# dependencies, so remove them before we set ourselves up. Also
# install pbr to avoid any setup_requires funkiness with
# pip/setuptools.
before_install:
  - pip uninstall -y nose mock
  - pip install pbr tox tox-travis

install: pip install -r doc/requirements.txt .[test]

script:
  # Conditional builds (related to env passed)
  - |
    case ${BUILD} in
        docs|pep8|cover)
            tox -e ${BUILD}
            ;;
        *)
            tox
            ;;
    esac

deploy:
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_existing: true
  provider: pypi
  user: __token__
  password:
    secure: qzFV1Z/ikoKIwO3/axDAvyF5putIsNzFU19CNz6hPM5kT+FbkgVND9E2QAYERo0Q2e5bZZhxdGCL0FHeYtWUx6rsBuqk/HDPZm/ltWXZ1TqU9XIJy0C7/igNG2ccBvmmY3WPGv0XezBjj0PGDMnPLpsZ7e9XT85EDnO9Ts4hbzIN+MfUQuAXbgfbl+L3ttA7XPXOFWl9Vi9GF9jVvvq16KSP6wKhCu6fQzd4S94m22YyRINEqL4f3t5X7NJeG2vHwhvRTP+9h100RDHwHea7jwA/HizRDJ1OwSxQ75CfqLWL7jatJtIMC0NDlM6ETFOOdDlAX/DZ8EsBmBBNioJyGZgltJlxJ2ObAZbhFfzzksql+XZ9XzUaCuL1Yf3mCfx5VL89wyUHW3iu8qItmxauDXcp6W36XPeh43m/m7h1vUVXenxdS3E0dVfl4tu0q2FZ48zSnUpi0OrF9yUKDQbMVfOPHCWX/Xi3pT682466xTTmN78I9c05/o7K7m1c9Vlb9u9UW8q0XYbM0zf9NyD2klVJ4Y2zz8+JQyjUJujB23gwm+SILFGprbeoa++yS+EpBQsMZSaZncxHiI4sn3c1b3ZYx4j53Kt5RKCSZa7LS9/VclCFwUik7rTqW7IrzuvvsApW7pNOzgqOplZlAqZOKMijXYvkrYdYQo41oY994ik=
